### ISSUE TITLE
verisim make error: cannot find "dtc"

### ISSUE THREAD

**Issue by filamoon** [riscv-boom/boom-template#31]
[CentOS 7]
Make fails in the verisim directory:

[error] (Thread-17) java.io.IOException: Cannot run program "dtc": error=2, No such file or directory
[error] java.io.IOException: Cannot run program "dtc": error=2, No such file or directory
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:138)
[error]         at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:117)
[error]         at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:96)
[error]         at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error]         at java.lang.UNIXProcess.forkAndExec(Native Method)
[error]         at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:138)
[error]         at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:117)
[error]         at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:96)
[error]         at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
^@^Cmake: *** [/data/boom-template/verisim/generated-src/boom.system.TestHarness.BoomConfig.fir] Error 130

**Comment by ccelio** [comment]
The error message mentions trying to run `dtc` but not being able to find it; you need to install `dtc` on your machine, which is the device tree compiler. 

It appears this setup information is in the readme for riscv-tools (https://github.com/riscv/riscv-tools#quickstart), but we should add this to the readme for riscv-boom and friends so other users don't run into this.
